### ISSUE TITLE
Multiple sidebars on one page

### ISSUE THREAD

**Issue by gyurmey2** [guoyunhe/sticky-scroller#9]
A very useful script for which I would like to thank you very much. I have a question, is there any way to add a sticky scroller to many elements on one page?

**Comment by guoyunhe** [comment]
You can try:

```js
const scroller1 = new StickyScroller(".my-sidebar-1");
const scroller2 = new StickyScroller(".my-sidebar-2");
```

**Comment by gyurmey2** [comment]
Thank you.

But is it possible to add dynamically (undefined number of sidebars) based on one class or tag (e.g. querySelectorAll)?

**Comment by guoyunhe** [comment]
```js
const scrollers = Array.from(document.querySelectorAll('.my-query')).forEach(elem => {
    return new StickyScroller(elem);
});
```

**Comment by gyurmey2** [comment]
Works great. Thank you very much for help.
